[workspace]
resolver = "2"
members = [
  "packages/cargo/*"
]

[workspace.dependencies]
cw-utils = "1"
cw2 = "1"
cw20 = "1"
cosmwasm-std = "1"
cosmwasm-schema = "1"
sei-cosmwasm = "0.4"
thiserror = "1"
borsh = "1"
bytemuck = {version = "1", features = ["derive"]}
serde = "1"
bincode = "1"
