[package]
name = "crownfi-cw-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = {workspace = true}
borsh = {workspace = true}
bytemuck = {workspace = true}
serde = {workspace = true}
bincode = {workspace = true}
