[package]
name = "crownfi-cw-common"
version = "0.4.0"
edition = "2021"

[features]
backtraces = ["cosmwasm-std/backtraces"]
cosmwasm_1_4 = ["cosmwasm-std/cosmwasm_1_4"]

[dependencies]
cw20 = {workspace = true}
cosmwasm-std = {workspace = true}
cosmwasm-schema = {workspace = true}
sei-cosmwasm = {workspace = true}
borsh = {workspace = true}
bytemuck = {workspace = true}
serde = {workspace = true}
bech32 = {workspace = true}
static_assertions = {workspace = true}

[dev-dependencies]
cw-multi-test = {workspace = true}
