[package]
name = "crownfi-cw-common"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw20 = {workspace = true}
cosmwasm-std = {workspace = true}
cosmwasm-schema = {workspace = true}
sei-cosmwasm = {workspace = true}
borsh = {workspace = true}
bytemuck = {workspace = true}
serde = {workspace = true}
bincode = {workspace = true}
bech32 = {workspace = true}
static_assertions = {workspace = true}

[dev-dependencies]
cw-multi-test = {workspace = true}
